import type { Intent } from '../../core/types.js';

/**
 * Frases prototipo por intencion: la data de entrenamiento del clasificador.
 *
 * Muchas estan escritas a proposito con formas que el lexico de regex NO
 * matchea. Ahi esta el valor: el clasificador semantico es la red de
 * contencion para el fraseo que nadie previo al escribir las reglas.
 */
export const PROTOTYPES: Partial<Record<Intent, string[]>> = {
  greeting: [
    'hola',
    'buenas che',
    'holaaa',
    'ey como va todo',
    'hey there',
    'good afternoon',
    'saludos',
    'buen dia a todos',
  ],
  farewell: [
    'un saludo grande',
    'seguimos despues',
    'corto aca',
    'chau nos vemos',
    'me voy yendo',
    'hasta la proxima',
    'listo por hoy',
    'bye for now',
    'talk to you later',
    'me desconecto',
  ],
  thanks: [
    'gracias crack',
    'mil gracias por la ayuda',
    'buenisimo te pasaste',
    'perfecto era eso',
    'thanks a lot',
    'that worked, appreciate it',
    'joya, gracias',
  ],
  smalltalk: [
    'nada importante',
    'ahi va',
    'bueno dale',
    'como viene la mano',
    'todo bien vos',
    'ahi andamos',
    'dale perfecto',
    'jaja que bueno',
    'nada, preguntaba nomas',
    'just checking in',
    'no worries',
  ],
  identity: [
    'de donde salis',
    'explicame que sos',
    'cual es tu proposito',
    'quien sos',
    'de que sos capaz',
    'contame que sabes hacer',
    'en que me podes ayudar',
    'cuales son tus capacidades',
    'what are you able to do',
    'tell me about yourself',
    'como es que funcionas por dentro',
  ],
  factual_qa: [
    'para que se usa un indice en una base',
    'que hace el protocolo DNS',
    'cuanto pesa un entero de 64 bits',
    'que quiere decir idempotente en una api',
    'que es la inyeccion de dependencias',
    'cual es la capital de noruega',
    'en que año salio react',
    'definime idempotencia',
    'que significa CORS',
    'quien invento el transistor',
    'cuanta memoria usa un puntero en C',
    'what does ACID stand for',
    'is postgres open source',
    'diferencia entre TCP y UDP',
  ],
  howto: [
    'cuales son los pasos para dejar andando redis',
    'que hay que hacer para firmar un binario',
    'como se deja corriendo un proceso en segundo plano',
    'por donde se empieza a estudiar go',
    'como configuro un dominio propio en vercel',
    'que pasos sigo para levantar postgres con docker',
    'necesito conectar mi app a stripe, por donde empiezo',
    'me explicas como montar un cron en linux',
    'cual es la forma correcta de instalar pnpm',
    'how do i set up ssh keys for github',
    'guiame para configurar eslint',
    'que tengo que hacer para publicar un paquete en npm',
  ],
  code_generate: [
    'preciso una estructura de datos tipo heap',
    'hace un verificador de numeros de documento',
    'quiero una capa de acceso http que reintente sola',
    'necesito una funcion de paginacion cursor-based',
    'necesito una funcion que parsee fechas ISO',
    'armame un endpoint POST para crear usuarios',
    'me falta un hook de react para debounce',
    'dame una clase que maneje reintentos con backoff',
    'quiero un script que renombre archivos en batch',
    'podes tirarme el tipado de esta respuesta',
    'write a middleware that validates jwt tokens',
    'i need a python generator that reads a csv lazily',
    'hacé un componente de tabla con paginacion',
    'me armas el schema de zod para este objeto',
  ],
  code_debug: [
    'la llamada externa nunca responde y corta por tiempo',
    'la pantalla de ajustes revienta al entrar',
    'a veces pasa y a veces no, es inestable',
    'IndexError: list index out of range',
    'el contenedor se queda trabado sin avanzar',
    'despues de actualizar la libreria dejo de compilar',
    'el proceso queda tomando cpu al 100 y no sale',
    'esto me esta tirando undefined y no se por que',
    'el test pasa local pero falla en CI',
    'se me cuelga el proceso despues de un rato',
    'me da 500 cuando mando el form',
    'la query devuelve vacio y en la base estan los datos',
    'segmentation fault al correr el binario',
    'why does my useEffect run twice',
    'getting ECONNREFUSED when connecting to redis',
    'el build explota sin decir nada util',
    'esto andaba ayer y hoy no, no toque nada',
    'memory leak en produccion, la ram sube y no baja',
  ],
  code_explain: [
    'que quiere decir esta linea',
    'como esta resuelto el cacheo aca dentro',
    'que esta haciendo esta expresion regular',
    'no me cierra como se arma este objeto',
    'que esta haciendo esta funcion exactamente',
    'no entiendo esta parte del codigo',
    'contame como funciona este modulo',
    'recorreme este archivo linea por linea',
    'para que sirve este decorador',
    'walk me through what this does',
    'que exporta este archivo',
    'por que usan un weakmap aca',
  ],
  refactor: [
    'hay logica repetida en varios lugares',
    'esto mezcla responsabilidades que deberian ir separadas',
    'el archivo se hizo enorme, conviene partirlo',
    'quiero despegar estas dos capas que quedaron pegadas',
    'toda esta cadena de condicionales se puede achicar',
    'pasemos estos callbacks a algo mas moderno',
    'quedo muy acoplado, hay que aflojarlo',
    'esto quedo ilegible, lo podes mejorar',
    'sacale la duplicacion a este archivo',
    'hay que partir esta funcion, hace demasiado',
    'pasemos esto a async await en vez de promesas',
    'lo quiero mas simple, sin tanta abstraccion',
    'moderniza este codigo que es de hace diez años',
    'clean this up please',
    'extraé esto a un modulo aparte',
    'unificá estas tres funciones que hacen casi lo mismo',
  ],
  research: [
    'que motor nos sirve mejor para datos de series de tiempo',
    'quiero ver el panorama de librerias de autenticacion',
    'postgres o mongo para este caso',
    'tiene sentido el esfuerzo de pasarnos a typescript',
    'kafka o rabbitmq, cual nos rinde mas',
    'que opciones hay en el mercado para esto',
    'conviene mas redis o memcached para nuestro caso',
    'quiero un panorama de las alternativas',
    'contame ventajas y desventajas de cada enfoque',
    'que usa la industria hoy para esto',
    'necesito entender el trade-off entre las dos',
    'evaluame estas tres librerias',
    'what are the main approaches to rate limiting',
    'vale la pena migrar o nos quedamos como estamos',
  ],
  planning: [
    'ordenemos las tareas del mes que viene',
    'como cortamos este epic en historias mas chicas',
    'definamos en que fases va el rediseño',
    'necesito secuenciar el trabajo del equipo',
    'como encaramos este proyecto',
    'necesito partir esto en tareas',
    'armemos el roadmap del trimestre',
    'por donde empiezo con esta migracion',
    'quiero definir la arquitectura antes de escribir codigo',
    'dividime esto en entregables',
    'help me break this down into milestones',
    'que orden le damos a las cosas',
    'diseñame la estructura del sistema',
  ],
  math: [
    'cuanto queda si le saco el 30 por ciento',
    'sumame todas estas cifras y dame el total',
    'cuanto representa esta parte del total',
    'cuanto me da si sumo estos numeros',
    'sacame el promedio de estos valores',
    'que porcentaje representa 340 sobre 1200',
    'resolveme esta ecuacion de segundo grado',
    'cuanto es el interes compuesto a cinco años',
    'necesito la mediana de esta serie',
    'how much is 15 percent of 2340',
    'convertime 250 dolares a pesos',
  ],
  translate: [
    'necesito el texto en italiano',
    'pasame el mensaje de error a otro idioma',
    'pasame esto al ingles',
    'como se dice esto en portugues',
    'necesito esta frase en frances',
    'traducime el readme completo',
    'put this in spanish please',
    'que quiere decir esto en castellano',
  ],
  summarize: [
    'resumime lo que se hablo en la reunion',
    'quiero una version breve para mandar al equipo',
    'condensa esto en unos pocos puntos',
    'hacemelo corto',
    'dame los puntos principales',
    'reducime esto a un parrafo',
    'que dice en criollo',
    'quiero la version de dos lineas',
    'give me the gist of this',
    'saca lo importante de este texto',
  ],
  creative: [
    'pensemos como llamar a esta funcionalidad',
    'necesito el copy de la pagina de inicio',
    'redactame un correo de presentacion',
    'inventame un nombre para el producto',
    'necesito ideas para el lanzamiento',
    'escribime un post para linkedin',
    'tirame diez titulos posibles',
    'armame un cuento corto para chicos',
    'brainstorm some taglines',
    'necesito un texto que venda esto',
  ],
  data_analysis: [
    'que nos muestran los numeros de retencion',
    'hay estacionalidad en esta serie',
    'que se ve en los datos de uso del mes',
    'que patron ves en estos numeros',
    'analizame las metricas del ultimo mes',
    'hay correlacion entre estas dos columnas',
    'que me dice este dataset',
    'sacame las tendencias de las ventas',
    'por que cayo el trafico en marzo',
    'what does this data tell us',
    'armame un grafico de esto',
  ],
  tool_action: [
    'arranca el server de desarrollo',
    'confirma estos cambios en el repositorio',
    'mostrame como esta el repo',
    'corre la bateria de pruebas',
    'subilo a produccion',
    'corré los tests a ver si pasan',
    'limpiá la tabla de sesiones',
    'mandale un mail al equipo',
    'hace el build y fijate si compila',
    'bajá ese servicio',
    'deploy this now',
    'fijate el git status del repo',
    'instalá las dependencias',
  ],
};

/** Corpus plano: [intencion, frase]. */
export function flatPrototypes(): Array<{ intent: Intent; text: string }> {
  const out: Array<{ intent: Intent; text: string }> = [];
  for (const [intent, phrases] of Object.entries(PROTOTYPES)) {
    for (const text of phrases ?? []) out.push({ intent: intent as Intent, text });
  }
  return out;
}
